import type { Metadata } from "next";
import Header from "../ui/header/header";


// export const metadata: Metadata = {
//   title: "%s | Biunatu",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}

    </>
  );
}
