import type { Metadata } from "next";
import Header from "../ui/header/header";

import Footer from "../ui/footer";

// export const metadata: Metadata = {
//   title: "%s | AmazingNature",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
